version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket mmw-graviton2 --output-template-file packaged-template.yml
  post_build:
    commands:
      - sam deploy
artifacts:
  files:
    - packaged-template.yml
    - appspec.yaml
    - appspec.yml
    - AppSpec.yaml