AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function

Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - arm64
      Code:
        ZipFile: |
          import json
          import platform


          def handler(event, _):
              if "Fail" in event:
                raise Exception("I was told to fail")
              platform_data = platform.uname()

              return {
                  "statusCode": 200,
                  "body": json.dumps(
                      {
                          "message": f"Welcome to a lambda running on an {platform_data.machine} machine using an {platform_data.processor} processor",
                      }
                  ),
              }
      FunctionName: graviton
      Handler: index.handler
      Role: !GetAtt Role.Arn
      Runtime: python3.9

  x86Version:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref Function

  armVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref Function

  current:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref Function
      FunctionVersion: !GetAtt x86Version.Version
      Name: current

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: "/"

Outputs:
  CurrentVersion:
    Value: !GetAtt x86Version.Version
